### model
model_name_or_path: ../hf-model/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset_dir: processed_data
dataset: hrn_train_sft
template: qwen
cutoff_len: 4096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: outputs/Conviction_Agent_Qwen7B
logging_steps: 10
save_steps: 500
save_total_limit: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
